version: '3'
services:
  redis:
    image: redis
    ports:
      - '7990:6379'
    volumes:
      - /srv/docker/redis:/var/lib/redis
  serverless-redis-http:
    ports:
      - '7991:80'
    image: hiett/serverless-redis-http:latest
    environment:
      SRH_MODE: env
      SRH_TOKEN: example_token
      SRH_CONNECTION_STRING: 'redis://redis:6379' # Using `redis` hostname since they're in the same Docker network.
